### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by rainbowdesign** [Zen-CODE/kivybits#19]
Hello zen-code,
sorry for waiting so long.

I wanted 2 examples:
One is how to make an isometric or non isometric grid with kivi to build stuff on it.
One example is Simcity2000.
What i have in mind i a clone of the old outpost game which looks like this:
http://www.ibiblio.org/GameBytes/issue18/flooks/outpost2.gif

The other example is this:
https://play.google.com/store/apps/details?id=com.rnet.robominer how to make this with kivy?

**Comment by Zen-CODE** [comment]
Hi
1. I believe the GridLayout docs do cover isometric vs. non-isometric via size hints. A grid implies vertical + horizontal dividers, and size_hint can make this non-isometric. You could also look at kivy3dlayout for 3d effects.
https://github.com/kpiorno/kivy3dgui

2. Background painting had now been covered.

3. The other examples requests are a bit vague and numerous. Please open a ticket per examples with greater detail.

Thansk
