### ISSUE TITLE
Scatter again

### ISSUE THREAD

**Issue by rainbowdesign** [Zen-CODE/kivybits#21]
Hei, i found this:

http://kivy.org/docs/api-kivy.uix.scatter.html#kivy.uix.scatter.Scatter.apply_transform

Parameters :  
trans: Matrix.
Transformation matix to be applied to the scatter widget.

anchor: tuple, defaults to (0, 0).
The point to use as the origin of the transformation (uses local widget space).

post_multiply: bool, defaults to False.
If True, the transform matrix is post multiplied (as if applied before the current transform).

Usage example:

from kivy.graphics.transformation import Matrix
mat = Matrix().scale(3, 3, 3)
scatter_instance.apply_transform(mat)
##### 

It would be good to add more informations about 
trans: Matrix.
Transformation matix to be applied to the scatter widget.

Where to look for what transformations can be used  and what syntax they have.

**Comment by rainbowdesign** [comment]
Okay i found the link its a bit hidden.

**Comment by rainbowdesign** [comment]
But i would like a description how to rotate and move it on a pc.

**Comment by tito** [comment]
Hi. Your original issue is not clear, nor the title, and talk about lot of things. Please use the kivy-user mailing list for discussion and seek application support.

**Comment by rainbowdesign** [comment]
Actually this is only a semi private conversation with Zencode. Only that when i linked the concerning kivy issue it was backlinked and zencode did not answer.... For the main issue i now created a support ticket feature request.

**Comment by Zen-CODE** [comment]
Okay, a lot of time has passed. Re: mouse right touch creating red dots, using the mouse to emulate multi-touch is here: https://kivy.org/docs/api-kivy.input.providers.mouse.html

Otherwise, sorry it took so long but to be honest, the kivy user group is where these discussion should take place. Please open discussion there if you still have issues.
