### ISSUE TITLE
Doesn't work with PyCharm 5.0.3 Prof

### ISSUE THREAD

**Issue by mjmare** [Zen-CODE/kivybits#22]
Error: Fail to load plugin descriptor from file PyCharm_kv_completion.jar

**Comment by Zen-CODE** [comment]
Sorry, only saw this now. Can't reproduce, but can only test in 2016.1. Works fine?

**Comment by Wunsz** [comment]
Happens also on Intellj 2016 2.4 and PyCharm 2016.2

**Comment by Zen-CODE** [comment]
@Wunsz. Strange. Using 2016.2.3 (latest at time of writing) it works (Linux Mint 18). Which OS are you using?

**Comment by Wunsz** [comment]
Debian 8 (Jessie) - also latets stable.
Also: InellJ 15.0.2 @ Windows 10 with Anniversary Update doesn't work - just checked.

The log however shows 2 warns:
2016-10-08 16:17:37,812 [ 232220]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: editor for id: editor.preferences.import 
2016-10-08 16:17:37,813 [ 232221]   WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: build for id: gradle.compiler 

But it doesn't look like a problem with the extension file.

**Comment by Zen-CODE** [comment]
Have confirmed this also works with the latest PyCharm on Windows 10. So it must be the PyCharm setup here, and not the jar file. Please re-open if there is evidence otherwise :-)

**Comment by OlafHaag** [comment]
I get the same error in Pycharm 2019.1.3 Pro on Win 10. Can't say I did anything special with the setup. I tried File->Settings->Plugins->Gear Icon->Install Plugin from Disk...

**Comment by Zen-CODE** [comment]
Sorry, I never could find the source of the error or reproduce it. If you can get any more details about the error (the warnings above are just warning and do not cause failure), I'd be happy to look into it, but without those, I'm pretty much stuck.

**Comment by OlafHaag** [comment]
Don't sweat it. Unfortunately I only get the window saying _Error: Fail to load plugin descriptor from file PyCharm_kv_completion.jar_

But I just opened the jar-file in 7-zip and extracted the keywords from PyCharm_kv_completion.jar\filetypes\Kivy.xml. And with a string-split, print statement and copy&paste it was really easy to set it up myself in Settings->Editor->FileTypes.
