### ISSUE TITLE
Request: update KV lang compatibility to Kivy v1.9.1

### ISSUE THREAD

**Issue by NumesSanguis** [Zen-CODE/kivybits#23]
It would be great if you could update PyCharm_kv_completion.jar to the latest v1.9.1 of Kivy :)
and even more awesome would be to update this page as well:
https://github.com/kivy/kivy/wiki/Setting-Up-Kivy-with-various-popular-IDE's
Because >=v1.9.1 doesn't use a kivy.bat anymore.

Thanks if you feel like doing it!

**Comment by Zen-CODE** [comment]
Thanks. The wiki has been updated. Thank goodness it's much easier now.

In terms of PyCharm autocompletion, what specifically were you looking for?

**Comment by NumesSanguis** [comment]
Thank you for your effort.

The PyCharm_kv_completion.jar was, I think, written for v1.8? So I guess some functions in Kivy have been added/changed in the mean time. Therefore I think this .jar was not up to date anymore.
However I see now that the .jar has been updated 9 days ago, so I guess it's good for now?

If I find some function in the .kv not recognized by PyCharm, I will post an update here.
