### ISSUE TITLE
 ERROR: ./gradlew failed!.

### ISSUE THREAD

**Issue by thegameguy** [Zen-CODE/kivybits#26]
hey, i'm really struggling with this very last problem during buildozer build that is [WARNING]: ERROR: ./gradlew failed!. error details: 

[INFO]:    Selecting java build tool:
[INFO]:    Detected highest available build tools version to be 28.0.2
[INFO]:        Building with gradle, as gradle executable is present
[DEBUG]:   -> running gradlew assembleDebug
[DEBUG]:    > Configuring > 0/1 projects > root project > Resolving dependenIncremental java compilation is an incubating feature.
[DEBUG]:    :preBuild UP-TO-DATE
[DEBUG]:    :preDebugBuild UP-TO-DATE
[DEBUG]:    :checkDebugManifest
[DEBUG]:    :prepareDebugDependencies
[DEBUG]:    :compileDebugAidl
[DEBUG]:    :compileDebugRenderscript
[DEBUG]:    :generateDebugBuildConfig
[DEBUG]:    :generateDebugResValues
[DEBUG]:    :generateDebugResources
[DEBUG]:    :mergeDebugResources
[DEBUG]:    :processDebugManifest
[DEBUG]:    :processDebugResources
[DEBUG]:    :generateDebugSources
[DEBUG]:    :incrementalDebugJavaCompilationSafeguard
[DEBUG]:    :javaPreCompileDebug
[DEBUG]:    :compileDebugJavaWithJavac
[DEBUG]:    :compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
[DEBUG]:    /home/kivy/test3/.buildozer/android/platform/build/dists/myapp/src/main/java/org/kivy/android/PythonService.java:97: error: cannot find symbol
[DEBUG]:            notification.setLatestEventInfo(context, serviceTitle, serviceDescription, pIntent);
[DEBUG]:                        ^
[DEBUG]:      symbol:   method setLatestEventInfo(Context,String,String,PendingIntent)
[DEBUG]:      location: variable notification of type Notification
[DEBUG]:    Note: Some input files use or override a deprecated API.
[DEBUG]:    Note: Recompile with -Xlint:deprecation for details.
[DEBUG]:    1 error
[DEBUG]:    :compileDebugJavaWithJavac FAILED
[DEBUG]:    
[DEBUG]:    FAILURE: Build failed with an exception.
[DEBUG]:    
[DEBUG]:    * What went wrong:
[DEBUG]:    Execution failed for task ':compileDebugJavaWithJavac'.
[DEBUG]:    > Compilation failed; see the compiler error output for details.
[DEBUG]:    
[DEBUG]:    * Try:
[DEBUG]:    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[DEBUG]:    
[DEBUG]:    BUILD FAILED
[DEBUG]:    
[DEBUG]:    Total time: 12.647 secs
Exception in thread background thread for pid 31613:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/kivy/.local/lib/python2.7/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/home/kivy/.local/lib/python2.7/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/kivy/.local/lib/python2.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
ErrorReturnCode_1:
 
  RAN: ./gradlew assembleDebug
 
  STDOUT:
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:incrementalDebugJavaCompilationSafeguard
:javaPreCompileDebug
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/home/kivy/test3/.buildozer/android/platform/build/dists/myapp/src/main/java/org/kivy/android/PythonService.java:97: error: cannot find symbol
        notification.setLatestEventInfo(context, serviceTitle, serviceDescription, pIntent);
                    ^
  symbol:   method setLatestEventInfo(Context,String,String,PendingIntent)
  location: variable notification of type Notification
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:compileDebugJavaWithJavac FAILED
 
FAILURE: Build failed with an exception.
 
* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 
BUILD FAILED
 
Total time: 12.647 secs
 
 
  STDERR:
 
 
[DEBUG]:    
[INFO]:    STDOUT (last 20 lines of 41):
      symbol:   method setLatestEventInfo(Context,String,String,PendingIntent) 
  location: variable notification of type Notification 
Note: Some input files use or override a deprecated API.   
Note: Recompile with -Xlint:deprecation for details.   
1 error
:compileDebugJavaWithJavac FAILED  
   
FAILURE: Build failed with an exception.   
   
* What went wrong: 
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.   
   
* Try: 
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. 
   
BUILD FAILED   
   
Total time: 12.647 secs
 
[INFO]:    STDERR:
   
[INFO]:    COMMAND:
cd /home/kivy/test3/.buildozer/android/platform/build/dists/myapp && ./gradlew assembleDebug
 
[WARNING]: ERROR: ./gradlew failed!
# Command failed: /usr/bin/python -m pythonforandroid.toolchain apk --debug --bootstrap=sdl2 --dist_name myapp --name 'My Application' --version 0.1 --package org.test.myapp --android_api 27 --minsdk 19 --private /home/kivy/test3/.buildozer/android/app --orientation portrait --window --copy-libs --arch armeabi-v7a --color=always --storage-dir=/home/kivy/test3/.buildozer/android/platform/build
#
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2

remedies i've tried include: - buildozer android clean - deleting .buildozer folder - reinstalling API 27 builds tools, API 28 build tools are the higest though! - reinstalling open jdk 8

**Comment by thegameguy** [comment]
having p4a.branch = master, solves the issue!

**Comment by Zen-CODE** [comment]
Thanks for posting back :-)
